# Generated by Django 2.1.5 on 2020-04-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainergroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='bells.TrainerPermission', verbose_name='permissions'),
        ),
    ]
